# -*- coding: utf-8 -*-
"""Distance between two points with tuples

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pp-YiEAs4NQggT-ypHypDbErzso7WrEK
"""

import math

# define A
coordinates = (4, 3)

# calculate
distance = math.sqrt((coordinates[0] - 0) ** 2 + (coordinates[1] - 0) ** 2)

print("Distance from origin:", distance)

