# -*- coding: utf-8 -*-
"""Fruit Dictionary Exercise

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pp-YiEAs4NQggT-ypHypDbErzso7WrEK
"""

# create first dictionary
fruit_prices = {
    'apple': 1500,
    'banana': 1000,
    'orange': 1200
}

# change banana price
fruit_prices['banana'] = 1100

# delete apple
del fruit_prices['apple']

# print dictionary
print(fruit_prices)

