# -*- coding: utf-8 -*-
"""Interrupted string practice

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pp-YiEAs4NQggT-ypHypDbErzso7WrEK
"""

x = 'Hi this is a string'

words_list = x.lower().split()
print(words_list)

