# -*- coding: utf-8 -*-
"""List Manipulation Exercise

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pp-YiEAs4NQggT-ypHypDbErzso7WrEK
"""

my_list = [1, 2, 3, 4, 5]

my_list.remove(3)

my_list.append(10)

print(my_list)

#If you want to use a function
def modify_list(lst):
    lst.remove(3)
    lst.append(10)
    return lst

my_list = [1, 2, 3, 4, 5]
result = modify_list(my_list)
print(result)