# -*- coding: utf-8 -*-
"""Python Wizard Exercise

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pp-YiEAs4NQggT-ypHypDbErzso7WrEK
"""

# define sets
SetA = {1, 2, 3, 4}
SetB = {3, 4, 5, 6}

# calculate unions
u = SetA | SetB  # یا SetA.union(SetB)

# calculate intersection
i = SetA & SetB  # یا SetA.intersection(SetB)

# show output
print(u)
print(i)

